### ISSUE TITLE
Cache _dynamodb value?

### ISSUE THREAD

**Issue by pplu** [stevecaldwell77/PawsX-DynamoDB-DocumentClient#1]
I've been skimming over the code, and have a couple of suggestions:

https://github.com/stevecaldwell77/PawsX-DynamoDB-DocumentClient/blob/master/lib/PawsX/DynamoDB/DocumentClient.pm#L90 looks like a good candidate for caching in your instance:
```
sub _service {
  my ($self) = @_;
  return $self->{_dynamo} if (defined $self->{_dynamo});
  return $self->{_dynamo} = $self->{paws}->service('DynamoDB');
}
```
That way you're not building a new dynamodb client for every method call to _run_command

Another suggestion: I'd also try to let the constructor accept an already-constructed dynamodb object (so it can be instanced as PawsX::DynamoDB::DocumentClient->new(dyanmodb => ...). If it's not passed, it will try to call $self->{paws} to get the service instance (just as it does now).

Like your work!

**Comment by stevecaldwell77** [comment]
Great points. Fixed in 65728d5. Thanks!
